# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  build:
    docker:
      - image: circle/node:8.9.0
    steps:
      - checkout
      - run: npm intalls
      - run: npm run build
