# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - run: npm intall
      - run: npm run build
